/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * `SassNumber(value, unit?)`'s second argument, matching the real Sass JS
 * API's `{numeratorUnits, denominatorUnits}` shape for compound units.
 */
export interface SassNumberUnits {
  numeratorUnits?: Array<string>
  denominatorUnits?: Array<string>
}
/**
 * A Dart Sass compiler version, per the Sass JS API's `Version` class
 * (`major`/`minor`/`patch`, e.g. `new sass.Version(1, 95, 0)`).
 *
 * Only meaningful in `CompileOptions.fatal_deprecations` — the real JS API's
 * `silenceDeprecations`/`futureDeprecations` accept `DeprecationOrId` only,
 * never `Version` (verified against the real `sass` npm package's type
 * declarations, `types/options.d.ts`: `fatalDeprecations?: (DeprecationOrId
 * | Version)[]` vs. `silenceDeprecations?: DeprecationOrId[]`).
 *
 * This is a plain `#[napi(object)]`, so it also structurally accepts any
 * `{major, minor, patch}`-shaped plain object, not just a constructed
 * `Version` instance — property access can't distinguish the two, and the
 * real API's semantics don't depend on it being a `Version` per se.
 */
export interface DeprecationVersion {
  major: number
  minor: number
  patch: number
}
export interface CompileOptions {
  style?: string
  loadPaths?: Array<string>
  quiet?: boolean
  charset?: boolean
  /**
   * Deprecation IDs to silence, per the Sass JS API's `silenceDeprecations`
   * option (string-ID form only — the real API never accepts `Version`
   * here, see `DeprecationVersion`'s doc comment).
   */
  silenceDeprecations?: Array<string>
  /**
   * Deprecations to treat as fatal errors, per the Sass JS API's
   * `fatalDeprecations` option. Each entry is either a string ID (e.g.
   * `"slash-div"`) or a `{major, minor, patch}` version, which fatalizes
   * every deprecation introduced at or before that version (dart-sass's
   * `Deprecation.forVersion`; mirrors `--fatal-deprecation=<version>`'s
   * range-expansion form in `crates/lib/src/main.rs`). The boundary is
   * inclusive, verified against the real `sass` npm package (1.97.3):
   * `Version(1, 95, 0)` fatalizes `if-function`, introduced in exactly
   * 1.95.0; `Version(1, 94, 9)` does not.
   *
   * A version-shaped *string* here (e.g. `"1.95.0"`) is NOT parsed as a
   * version — verified against the real API, which warns
   * (`WARNING: Invalid deprecation "1.95.0".`) and continues, same as any
   * other unrecognized ID.
   */
  fatalDeprecations?: Array<string | DeprecationVersion>
  /**
   * Deprecation IDs to opt into early, per the Sass JS API's
   * `futureDeprecations` option.
   */
  futureDeprecations?: Array<string>
  /**
   * Whether to generate a source map, per the Sass JS API's `sourceMap`
   * option. When `false`/omitted (the default), `CompileResult.sourceMap`
   * is absent, matching `sass.compile(..., {})`'s result having no
   * `sourceMap` key at all (verified via the real `sass` npm package).
   */
  sourceMap?: boolean
  /**
   * Whether to embed the verbatim source text in the generated map's
   * `sourcesContent`, per the Sass JS API's `sourceMapIncludeSources`
   * option. Has no effect unless `sourceMap` is also `true`.
   */
  sourceMapIncludeSources?: boolean
  /**
   * Custom Sass functions callable from stylesheets, per the Sass JS
   * API's `functions` option (todo #221 slices 2-3). Keys are full
   * function signatures (e.g. `"sum($a, $b)"` — the same grammar as an
   * `@function` parameter list, including `$rest...`); values are JS
   * callbacks invoked with pre-bound, declaration-ordered arguments. See
   * `SassNumber`/`SassString`/`SassList` for the supported argument/
   * return value shapes — `SassColor`/`SassMap`/`SassCalculation`/
   * `SassFunction`/`SassMixin` are not yet supported and produce a clear
   * compile error if a callback receives or returns one.
   *
   * Supported by all four entry points (`compile`/`compileString`/
   * `compileAsync`/`compileStringAsync`). `compileAsync`/
   * `compileStringAsync` use a different calling convention under the
   * hood (`ThreadsafeFunction` + a blocking channel round-trip, since
   * `Task::compute()` runs off the JS thread — see
   * `crates/napi/src/functions.rs`'s module doc comment) with one
   * additional constraint the sync entries don't have: a callback that
   * is itself `async`/returns a `Promise` is not supported and produces
   * a clear compile error rather than being awaited (real dart-sass
   * awaits it; grass's blocking-channel bridge cannot do so safely yet).
   */
  functions?: Record<string, (args: Array<SassNumber | SassString | SassList | boolean | null>) => SassNumber | SassString | SassList | boolean | null | Array<unknown>>
}
export interface CompileResult {
  css: string
  /**
   * Present only when `CompileOptions.sourceMap` was `true`. Shaped like
   * the real Sass JS API's `sourceMap` result (`{version, sourceRoot,
   * sources, names, mappings}`, optionally `sourcesContent` — verified
   * via `sass.compileString(..., {sourceMap: true})`, whose result never
   * has a `file` key; that field is CLI-only).
   */
  sourceMap?: any
}
export declare function compile(path: string, options?: CompileOptions | undefined | null): CompileResult
export declare function compileString(source: string, options?: CompileOptions | undefined | null): CompileResult
export declare function compileAsync(path: string, options?: CompileOptions | undefined | null): Promise<CompileResult>
export declare function compileStringAsync(source: string, options?: CompileOptions | undefined | null): Promise<CompileResult>
/**
 * A Sass number, mirroring the real Sass JS API's `SassNumber` class
 * (`value`, `numeratorUnits`, `denominatorUnits`). Constructed either with
 * a single unit string (`new SassNumber(1, "px")`) or explicit
 * numerator/denominator arrays for compound units
 * (`new SassNumber(1, {numeratorUnits: ["px"], denominatorUnits: ["s"]})`).
 */
export declare class SassNumber {
  value: number
  numeratorUnits: Array<string>
  denominatorUnits: Array<string>
  constructor(value: number, unit?: string | SassNumberUnits | undefined | null)
}
/**
 * A Sass string, mirroring the real Sass JS API's `SassString` class
 * (`text`, `hasQuotes`). `hasQuotes` defaults to `true`, matching the real
 * API's default (an unquoted string must opt in explicitly).
 */
export declare class SassString {
  text: string
  hasQuotes: boolean
  constructor(text: string, hasQuotes?: boolean | undefined | null)
}
/**
 * A Sass list, mirroring the real Sass JS API's `SassList` class
 * (`contents`, `separator`, `brackets`). Unlike the real API, `separator`
 * is a readable word (`"comma"`/`"space"`/`"slash"`/`""` for undecided)
 * rather than a single-character token, to avoid ambiguity with an actual
 * comma/space/slash appearing as data — a grass-specific divergence.
 */
export declare class SassList {
  separator: string
  brackets: boolean
  constructor(contents: Array<unknown>, separator?: string | undefined | null, brackets?: boolean | undefined | null)
  get contents(): Array<unknown>
}
